### ISSUE TITLE
Kanalidee: amilios Blogfreunde

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#1]
Einmal pro Woche darf ein Blogger eine Kollektion anlegen, die wir dann promoten.

**Comment by phmLabs** [comment]
Hat bei phphatesme wunderbar geklappt, um Leute auf die Seite zu bekommen. Ggf könnte man auch bekannte Menschen nehmen z.B. Lars Jankowfsky.

**Comment by phmLabs** [comment]
Blogger:

Fashion/Lifestyle: bradsticks.com, style-mom.de, amilio.de, stern_sofa, roomido

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#162
