### ISSUE TITLE
Startseite könnte auch ein Kanal sein

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#101]
Einfach auch anderen Kanäle verlinkbar machen und fertig.

**Comment by phmLabs** [comment]
Channel Element könnte da Attribut theme haben. 

Einspaltig. Zweispaltig

**Comment by phmLabs** [comment]
Ist es. Kanal 30.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#101
