### ISSUE TITLE
Layout: Meine Kanäle

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#102]
Sieht nicht gut aus.

Damit die Seite gefällt wird, sollten wir einen Kanal pflegen, der eingebunden wird "Interessante Kanäle"

**Comment by phmLabs** [comment]
Layout wurde angepasst. Jetzt verwenden wir das Standard-Layout für Kanäle in Listen.

**Comment by phmLabs** [comment]
Um die "Interessante Kanäle" Liste anzuzeigen muss noch die ID der Kanalliste geändert werden. Dazu muss aber das CSS in eine Klasse gepackt werden.

**Comment by phmLabs** [comment]
Fertig. 

amilio __favChannel wird jetzt eingeblendet.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#102
