### ISSUE TITLE
Kanäle können auch fremde Kanäle verlinken

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#103]
So können wir auch die Startseite und die "Meine Kanäle"-Seite pflegen

**Comment by phmLabs** [comment]
Sollte über ChannelElement bereits gehen.

**Comment by phmLabs** [comment]
Muss erstmal nur über pma funktionieren. Auf diese Art kann man bereits die Startseite befüllen.

**Comment by phmLabs** [comment]
geht über pma

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#103
