### ISSUE TITLE
Meta Tag Description

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#105]
momemtan laufen die Kanäle ganz krude in die Google Suche rein.

**Comment by phmLabs** [comment]
https://www.google.de/search?q=site%3Awww.amilio.de&oq=site%3Awww.amilio.de&aqs=chrome..69i57j69i58.3783j0j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=site:www.amilio.de

**Comment by phmLabs** [comment]
Für Kanäle erledigt.

**Comment by thorbenheins** [comment]
Was heißt hier krude? Hab probiert das über die Date Range Suche nachzuvollziehen, waren eigentlich nur wenig hits?

**Comment by phmLabs** [comment]
Sowas:

amilio.de
www.amilio.de/channels/
Wollen Sie dieses Element wirklich löschen? Ja Nein. Über uns; Blog; Nutzerkanäle. Starte einen Kanal. Meine Kanäle · Abmelden. Anmelden. Username

**Comment by thorbenheins** [comment]
Alles klar.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#105
