### ISSUE TITLE
Layout: Kanallayout kaputt, wenn kein Bild angegeben ist

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#106]

**Comment by phmLabs** [comment]
Breite des Bildes sollte in dem Zuge auch angepasst werden.

**Comment by phmLabs** [comment]
Done.

**Comment by phmLabs** [comment]
Muss man aber aufpassen, dass das Bild im richtigen Format ist.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#106
