### ISSUE TITLE
Seite: Über uns

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#11]
Personen:
- Nils Langner (Grüner, CEO)
- Thorben Heins (Leiter Shopintegration)
- Stefanie Langner (Head of Content)

**Comment by phmLabs** [comment]
Würde ich gerne über den Blog irgendwie befüllen.

**Comment by phmLabs** [comment]
Seite eingerichtet. Kann über Wordpress editiert werden.

**Comment by phmLabs** [comment]
Auch als Kanal?

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#11
