### ISSUE TITLE
Bug: Eine Kollektion sollte keine Unterkollektion haben dürfen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#111]

**Comment by phmLabs** [comment]
Im ersten Schritt reicht es, wenn es per css ausgeblendet wird.

**Comment by phmLabs** [comment]
Im Template ausgebaut. Wenn jemand es per eigenem AJAX-Call hinbekommt, dann hat er es auch verdient und wenn wir es ihm dann irgendwann wegnehmen ist er selbst schuld.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#111
