### ISSUE TITLE
Weiterleitung amilio.de nach www.amilio.de

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#124]

**Comment by phmLabs** [comment]
done. mal schauen, was local passiert :)

**Comment by thorbenheins** [comment]
Man muss dann auch seine /etc/hosts anpassen und die httpd.conf anpassen.

**Comment by phmLabs** [comment]
Ich hab bei mir die Zeile erstmal wieder rausgeworfen lokal. Aber man kann ja auch eine Domain-Weiche einbauen, wenn man mal Zeit hat. Wäre sicherlich viel sauberer.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#124
