### ISSUE TITLE
min-height bei kleinen Seiten setzen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#136]
http://www.amilio.de/we/ueber-uns/

hier sollte der footer zB am Ende der Seite sein.

**Comment by phmLabs** [comment]
Done mit der Anleitung:

http://stackoverflow.com/questions/15021573/css-get-div-to-take-up-100-body-height-minus-fixed-height-header-and-footer

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#136
