### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#139]
Die Seite sollte sicher sein.

**Comment by thorbenheins** [comment]
Wildcard Certificate? Vermutlich schon, wenn wir blog.amilio.de haben, oder?

**Comment by phmLabs** [comment]
Moin :) Glaube der Blog muss nicht https sein, oder? Kommt einfach auf den Preis an denke ich.

**Comment by thorbenheins** [comment]
Dann sollten wir nur per SSH Tunnel auf das Blog Backend gucken...

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#139
