### ISSUE TITLE
Login via AJAX

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#140]
http://www.webtipblog.com/adding-an-ajax-login-form-to-a-symfony-project/

Es sollte auch der Cookie gesetzt werden.

**Comment by phmLabs** [comment]
http://stackoverflow.com/questions/9166930/using-symfony2s-accessdeniedhandlerinterface

**Comment by phmLabs** [comment]
Werde es wohl über ein iFrame machen.

**Comment by phmLabs** [comment]
Done. 

Wird jetzt über ein iFrame geregelt, so dass bei falschem Passwort oder Username alles im Fenster bleiben kann.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#140
