### ISSUE TITLE
Runbook Dokumentation

### ISSUE THREAD

**Issue by thorbenheins** [thorbenheins/miolia#143]
Wir brauchen ein Runbook, in dem wir alles festhalten, was wir für DevOps so brauchen.

**Comment by thorbenheins** [comment]
Zum Beispiel diese Issues wären dokumentationswürdig: #40, #47, #101

**Comment by phmLabs** [comment]
Wir brauchen auch einen DB-Dump im Repo denke ich. Momentan machen wir ja alles über Kanäle und wenn zB der 30 fehlt geht kaum was.

**Comment by thorbenheins** [comment]
Das ist mir auch schon aufgefallen, könnte man evtl auch "sauberer" über fixtures lösen?

**Comment by phmLabs** [comment]
Habe den Meilenstein entfernt.

**Comment by phmLabs** [comment]
https://github.com/thorbenheins/miolia/wiki/Runbook

**Comment by thorbenheins** [comment]
Dann sollte ich wohl mal ein privates github repo machen, oder?

On Dec 30, 2014, Nils Langner notifications@github.com wrote:

> https://github.com/thorbenheins/miolia/wiki/Runbook
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thorbenheins/miolia/issues/143#issuecomment-68330338

## 

Sent from my "smart"-phone, please disregard the typos!

**Comment by phmLabs** [comment]
Würde das gerne auf den phmLabs-Account legen.

**Comment by thorbenheins** [comment]
Das ganze repo? Einfach forken  oder? Dann check ich neu aus...

On Dec 30, 2014, Nils Langner notifications@github.com wrote:

> Würde das gerne auf den phmLabs-Account legen. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thorbenheins/miolia/issues/143#issuecomment-68341325

## 

Sent from my "smart"-phone, please disregard the typos!

**Comment by phmLabs** [comment]
https://github.com/thorbenheins/miolia/wiki/Runbook

**Comment by phmLabs** [comment]
Repo ist fertig und umgezogen. Wollen wir das hier leeren? Die issues sind ja noch nicht umgezogen.

**Comment by thorbenheins** [comment]
Ja können wir machen. 

On Jan 2, 2015, Nils Langner notifications@github.com wrote:

> Repo ist fertig und umgezogen. Wollen wir das hier leeren? Die issues
> sind ja noch nicht umgezogen. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/thorbenheins/miolia/issues/143#issuecomment-68565017

## 

Sent from my "smart"-phone, please disregard the typos!

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#143
