### ISSUE TITLE
Hurricane 2015

### ISSUE THREAD

**Issue by thorbenheins** [thorbenheins/miolia#145]

**Comment by phmLabs** [comment]
Schöne Idee.

Hab einen Kanal rund um Musik "Das Mixtape". Da könnte das passen.

**Comment by thorbenheins** [comment]
Vielleicht ist FKPScorpio ein interessanter Partner an der Stelle.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#145
