### ISSUE TITLE
Html-Tags in Produktbeschreibung

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#148]
Amazon hat solche Tags drinnen und wir filtern sie nicht raus. Sieht irgndwie doof aus.

https://www.dropbox.com/s/b2uojvzupkmqxct/Screenshot%202014-12-29%2016.04.08.jpeg?dl=0

**Comment by phmLabs** [comment]
Die Diskussion dazu:
https://www.facebook.com/nils.langner/posts/995511820463158?pnref=story

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#148
