### ISSUE TITLE
Bug: In eigenen Kanal übernehmen wenn nicht angemeldet

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#151]
Zeigt im modalen Fenster die "not allowed"-Seite an

**Comment by phmLabs** [comment]
Wieder über class: user class: anonymous

**Comment by phmLabs** [comment]
Link wird ausgeblendet.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#151
