### ISSUE TITLE
Modal Window hat nicht immer die richtige Breite

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#161]
Zum Beispiel beim Anlegen eines Kanals

**Comment by phmLabs** [comment]
Sieht so aus, als ob da einfach die breitenangabe fehlt.

**Comment by phmLabs** [comment]
Edit Produkt fehlt noch.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#161
