### ISSUE TITLE
Layout: Logo im Header zentrieren

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#19]
Das Logo im Header sollte zentriert sein auch aus dem Header herausragen.

**Comment by phmLabs** [comment]
Sieht irgendwie gar nicht so geil aus, wie ich mir das vorgestellt habe :)

**Comment by phmLabs** [comment]
Im schmalen Layout nicht mehr notwendig

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#19
