### ISSUE TITLE
Kollektion

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#21]
Es sollte möglich sein, dass Nutzer einzelne Produkte gruppieren und in Kollektionen zusammenzufassen.

**Comment by phmLabs** [comment]
Geht.

Es fehlt noch:
- Layout in Listenansicht
- Rücklink -> diese Kollektion gehört zu Kanal "www.thewebhatesme.com"

**Comment by phmLabs** [comment]
Rücklink fertig, aber noch nicht ge"hübscht"

**Comment by phmLabs** [comment]
Fertig.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#21
