### ISSUE TITLE
Kanal: Pagination

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#22]
Es muss möglich sein die Anzahl der Artikel pro Seite fixieren und über eine Paginierung die nächsten Artikel anzusehen.

**Comment by phmLabs** [comment]
Kann glaube ich auf Post-Launch geschoben werden, da wir ja noch keine großen Listen haben und wir den Varnish noch fit machen wollen als nächstes.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#22
