### ISSUE TITLE
Blog: Wordpress aufsetzen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#23]
Unter www.amilio.de/blog einen Blog erreichbar machen

**Comment by phmLabs** [comment]
Done. Layout und so fehlt noch. Bin mir momentan auch noch nicht so sicher, ob wir das beim Start brauchen.

**Comment by thorbenheins** [comment]
Was muss im Backend dafür getan werden, Datenbank etc?

**Comment by phmLabs** [comment]
Die wp-config.php anpassen mit deinen Datenbankdaten und dann /blog aufrufen.

**Comment by phmLabs** [comment]
Blog nach Blog.anilio.de verschoben.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#23
