### ISSUE TITLE
Nutzerkanäle

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#26]
Auflisten von besonderen Kanälen:
- Channels of the Week -> sollen schön gelayoutet sein (kuratiert) 
- Neuste 5

**Comment by phmLabs** [comment]
Sieht schon mal gut aus. Werde heute Abend mal die ersten 5 Channels of the Week einpflegen.
- Zuhause.
- Movie addicted.
- Gentlemen's Club.
- Eltern. Kinder. Familie.
- Fashion Victim.

**Comment by phmLabs** [comment]
http://www.amilio.de/channels/

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#26
