### ISSUE TITLE
Seite: Startseite

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#28]
Zu klären:
- was kommt drauf?
- wie sieht sie aus?

**Comment by phmLabs** [comment]
Sieht ganz gut aus: http://www.zalando.de/damen-home/

**Comment by phmLabs** [comment]
Erster "Kasten" starte deinen eigenen Kanal.

**Comment by phmLabs** [comment]
Erster Versuch des oberen Teil der Startseite.

http://www.amilio.de/

**Comment by phmLabs** [comment]
Würde gerne noch die beliebtesten Produkte mit auf die Startseite bekommen.

Beliebt = In den meisten Kanälen?

**Comment by phmLabs** [comment]
Glaube das sieht ganz gut aus. Habe auch die Breite angepasst. Sind jetzt im gleichen Raster wie shop love.

![homepage](https://cloud.githubusercontent.com/assets/650537/5407783/050c7660-81ce-11e4-824c-f9aaa9284af2.png)

**Comment by phmLabs** [comment]
Einmal Feedback von @thorbenheins bitte :)

Die Schriftart vond en Zwischenüberschriften soll noch anders und aus zentriert. Logo im Footer wird auch neu.

**Comment by phmLabs** [comment]
Ich stelle meine Notizen zur Startseite auch mal hier ein:
- Vielleicht eine kleine Liste von Produkten noch hinzufügen, dafür mehr
- Facebook und Twitter prominenter (vll. wie bei whm)
- Blog-Artikel und Anleitungen ebensfalls auf Startseite
- Facebook- und Twitter-Links auch in Footer
- Schriftart der ersten Box anpassen
- 5er Grid auch bei Kanalseiten verwenden
- Newsletteranmeldung (ggf. auch als PopUp)

**Comment by phmLabs** [comment]
Würde das Ticket zumachen, weil ich denke für den Start sieht das gut genug aus, was wir gerade haben. 

PS: Mache aber noch ein anderes auf, das nicht im Launch-Scope ist.

**Comment by thorbenheins** [comment]
Ist leider in der Flut der Mails untergegangen. Gefällt mir sehr gut!

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#28
