### ISSUE TITLE
Double-Opt-In bei Anmeldung

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#29]
fosUserBundle sollte das können. Wahrscheinlich bedeutet dies auch, dass man die E-Mail-Inhalte noch pflegen muss.

**Comment by phmLabs** [comment]
Aktiviert.

Templates müssen noch angepasst werden.

**Comment by phmLabs** [comment]
<pre>fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: "Amilio\CoreBundle\Entity\User"
    registration:
        confirmation:
            from_email: # Use this node only if you don't want the global email address for the confirmation email
                address: register@amilio.de
                sender_name: "amilio - Registrierung"
            enabled:    true # change to true for required email confirmation
            template:   FOSUserBundle:Registration:email.txt.twig</pre>

**Comment by phmLabs** [comment]
E-Mail-Text eingerichtet.

Es fehlen aber noch schön gelayoutete "du bist jetzt angemeldet" Seiten

**Comment by phmLabs** [comment]
Done. Alles schön.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#29
