### ISSUE TITLE
Produktlinks mit Partner-ID bestücken

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#32]
Unsere Amazon-ID muss im ersten Schritt hinterlegt werden, falls sie nicht vom Nutzer übersteuert wird.

**Comment by phmLabs** [comment]
Zumindest wird jetzt schon mal die ASIN mit weggespeichert.

foreignId = "amazon:#asin#";

**Comment by phmLabs** [comment]
Done.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#32
