### ISSUE TITLE
Produkt: Rechte

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#35]
Wer darf was?

In Symfony2 bestimmte Aktionen verbieten

**Comment by phmLabs** [comment]
owner an produkt ranpacken.
editieren nur wenn owner ist.

**Comment by phmLabs** [comment]
Owner rangepackt.

**Comment by phmLabs** [comment]
Versuche ich heute Abend noch zu machen.

**Comment by phmLabs** [comment]
Done.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#35
