### ISSUE TITLE
Kanal: Header-Bilder zurechtschneiden

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#39]
Es sollte möglich sein, wie bei Facebook die Headergrafik zurecht zu schneiden.

**Comment by phmLabs** [comment]
Tipp Thorben: http://mattketmo.github.io/darkroomjs/

**Comment by phmLabs** [comment]
@thorbenheins Soll ich ein Layout erstellen?

**Comment by phmLabs** [comment]
Habe grad so die Idee, dass man ein Bild hochladen kann und aus dem dann vier Bilder croppen muss. So könnte man dann Teaserbilder von User erstellen lassen, die wir z.B. auf der Startseite verwenden können.

**Comment by phmLabs** [comment]
Gibt keine headerbilder mehr

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#39
