### ISSUE TITLE
Server aufsetzen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#40]
- nginx
- memCached
- Varnish
- MailServer
- MySQL
- Neuste PHP-Version

**Comment by phmLabs** [comment]
http://www.server4you.de/vserver/#compare

Plus X5 entspricht ca. 10 EUR im Monat und ich glaube, dass das für den Anfang ausreichen ist, wenn man sich noch einen Varnish installiert.

Bilder kommen ja in der ersten Ausbaustufe gar nicht von uns.

**Comment by phmLabs** [comment]
Habe ich heute morgen bestellt. Sollte ca. 4 Std dauern, bis er uns zur Verfügung steht.

**Comment by phmLabs** [comment]
Alles bis auf den Varnish installiert. Doctrine auf memcache umgestellt.

Morgen hilft Sven mit beim Varnish, dann sollten die Bilder recht schnell ausgeliefert werden :)

**Comment by phmLabs** [comment]
PHP 5.6 -> https://pascalebeier.de/php-5-6-auf-debian-wheezy-installieren/

**Comment by phmLabs** [comment]
http://stackoverflow.com/questions/19335305/composer-install-error-requires-ext-curl-when-its-actualy-enabled

**Comment by phmLabs** [comment]
http://stackoverflow.com/questions/12543236/date-default-timezone-get-it-is-not-safe-to-rely-on-the-systems-timezone-set

**Comment by phmLabs** [comment]
Done.

**Comment by phmLabs** [comment]
#!/bin/bash

file="/etc/apache2/sites-available/vhost-$1"

if [ -f $file ];
then

  echo -e "\033[33;32m $file already exists. Seems like $1 already exists."

else

  mkdir -p /var/www/vhost/$1/htdocs

  cp /root/templates/vhost/default /etc/apache2/sites-available/vhost-$1
  ln -s /etc/apache2/sites-available/vhost-$1 /etc/apache2/sites-enabled
  sed -i s/VHOST_DOMAIN/$1/g /etc/apache2/sites-available/vhost-$1

  echo -e "\033[33;32m Domain $1 created. Please restart your apache server."

fi

tput sgr0

**Comment by phmLabs** [comment]
http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#40
