### ISSUE TITLE
Kanal: Diesem Kanal folgen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#41]
Es muss möglich sein einem Kanal zu folgen.

Zusätzlich muss auf der Seite /user/ ein Stream mit allen Inhalten alle gefolgten Kanäle existieren.

**Comment by phmLabs** [comment]
Implementiert. 

Favoriten werden in DB gepeichert, aber auch in Cookie, so dass die Channel-Seite immer noch aus dem Cache kommen kann. Kleiner Geniestreich ;)

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#41
