### ISSUE TITLE
Bug: Keine Umlaute in der URL erlauben

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#45]
Eigentlich sollte die verwendete Bibliothek es rausfiltern. Tut sie aber nicht.

**Comment by phmLabs** [comment]
Eigentlich nicht launchrelevant, da wir eine Weiterleitung drinnen haben, die das nachher wieder geradebiegt.

**Comment by phmLabs** [comment]
'transliterate' => true,

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#45
