### ISSUE TITLE
Bug: Kanal mit Produkten löschen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#46]
An exception occurred while executing 'DELETE FROM Channel WHERE id = ?' with params [28]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`amilio/ChannelElement`, CONSTRAINT `FK_44C9C28072F5A1AA` FOREIGN KEY (`channel_id`) REFERENCES `Channel` (`id`))

**Comment by phmLabs** [comment]
Behoben.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#46
