### ISSUE TITLE
Bug: app_dev.php ist nicht gesichert

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#47]
Sollte wieder ein Schutz drauf sein. Ggf. HTTP BASIC AUTH

**Comment by phmLabs** [comment]
https://www.mybboard.de/forum/thread-13420.html

**Comment by phmLabs** [comment]
<Files app_dev.php>
        AuthName "Development Environment"
        AuthType Basic
        AuthUserFile /var/www/vhost/www.amilio.de/web/.htpasswd
        require valid-user
</Files>

**Comment by phmLabs** [comment]
Done: Passwort auf Anfrage.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#47
