### ISSUE TITLE
Produkt: Social Media Integration

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#48]
Die Produktseite sollte mindestens facebook, google# und pinterest beinhalten.

**Comment by phmLabs** [comment]
Könnte ein wenig größer werden, da wir uns überlegen müssen, wohin der Link zum Produkt wirklich führt.

**Comment by phmLabs** [comment]
Links sind richtig gesetzt.

Verschiebe das Ticket aber doch erstmal nach Post-Launch, da ich noch nicht weiß, wie wir Ajax und JavaScript verknüpfen können.

**Comment by phmLabs** [comment]
http://support.sharethis.com/customer/portal/questions/846112-setting-urls#sthash.76HaVF1O.dpbs

**Comment by phmLabs** [comment]
Done.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#48
