### ISSUE TITLE
Bug: Cookie-Lebenszeit nicht gleich by fosUserBundle und Cookies

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#50]
Die einen laufen aus, die anderen nicht.

**Comment by phmLabs** [comment]
Eigentlich sollte man sich so die Lebenszeit im Controller ausgeben können, aber ich bekomme immer nur string(1) "0"

```
    $session = $this->get('session');
    var_dump($session->getMetadataBag()->getLifetime());
```

**Comment by phmLabs** [comment]
Wenn FOS einen nicht reinlässt, löschen wir die Cookies. Fertig.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#50
