### ISSUE TITLE
Produkt: In eigenen Kanal übernehmen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#55]
Optisch stelle ich es mir ganz nett vor, wenn es auch direkt in der Produktliste geschehen könnte.

**Comment by phmLabs** [comment]
Ist schon viel passiert, wurde aber noch nicht in neue ChannelElement-Struktur umgezogen

**Comment by phmLabs** [comment]
Implementiert

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#55
