### ISSUE TITLE
Weiterleitung http://amilio.de nach www.amilio.de

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#58]

**Comment by phmLabs** [comment]
```
RewriteEngine On

RewriteCond %{HTTP_HOST} !^www\.amilio\.de$ [NC]
RewriteRule ^(.*)$ http://www.amilio.de/$1 [L,R=301]
```

**Comment by phmLabs** [comment]
Konnte ich gestern über Plesk machen. Leider ist der Server heute schon das erste mal down. Ich schließe es trotzdem.

**Comment by thorbenheins** [comment]
Keine Ahnung ob das Performance Unterschiede macht, aber ich hätte jetzt einen ServerAlias vergeben?

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#58
