### ISSUE TITLE
Kanaltemplates

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#6]
Es soll die Möglichkeit geben, dass ein Nutzer sich unter verschiedenen Templates das aussuchen kann, welches am besten zu seinen Produkten passt.

**Comment by phmLabs** [comment]
Habe mal das Feld "theme" zum Kanal hinzugefügt, weil ich ein neues Layout für die Ansicht machen will und das alte nicht weg soll.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#6
