### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#68]
Für Google sollte eine Sitemap existieren, damit alle Seiten gefunden werden.

**Comment by phmLabs** [comment]
http://www.sitemaps.org/de/protocol.html

Brauchen aber auch das Last Modified Datum an den Kanälen.

**Comment by phmLabs** [comment]
Wieder in v1.0 geschoben, da derzeit kaum etwas in den google index läuft. 

last_mod ist aber optional habe ich gesehen. Das Problem müssen wir also noch nicht lösen.

**Comment by phmLabs** [comment]
http://www.amilio.de/sitemap/sitemap.xml
http://www.amilio.de/sitemap/channel.xml
http://www.amilio.de/sitemap/product.xml

hab's auch schon bei den Google Webmaster Tools eingereicht.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#68
