### ISSUE TITLE
Bei einer Auflösung von 1440x900 nutzbar sein

### ISSUE THREAD

**Issue by thorbenheins** [thorbenheins/miolia#80]

**Comment by thorbenheins** [comment]
![screen shot 2014-12-11 at 22 08 35](https://cloud.githubusercontent.com/assets/1863209/5402679/bbe5d860-8186-11e4-9d4c-069a83c6d6e6.png)
![screen shot 2014-12-11 at 21 42 52](https://cloud.githubusercontent.com/assets/1863209/5402680/bbe7a8b6-8186-11e4-8c5e-31615bd9a4eb.png)

**Comment by thorbenheins** [comment]
Der standard Header scheint zu breit zu sein. Wenn sich ein Modal öffnet, ist ein Scrollen nicht erlaubt.

**Comment by phmLabs** [comment]
Das liegt daran, dass wir das Logo rausgeschoben haben. Würde ich in die Mitte schieben.

**Comment by phmLabs** [comment]
Passt es jetzt so?

**Comment by phmLabs** [comment]
Done.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#80
