### ISSUE TITLE
jQuery wird doppelt geladen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#85]
Einmal intern und einmal von google-Hosted

**Comment by thorbenheins** [comment]
Ist doch erledigt oder?

**Comment by phmLabs** [comment]
Ja, da hatten wir etwas falsch konfiguriert und assetic hat sich immer wieder neu inkludiert.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#85
