### ISSUE TITLE
Seite: Startseite v2

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#86]
Ich stelle meine Notizen zur Startseite auch mal hier ein:

Vielleicht eine kleine Liste von Produkten noch hinzufügen, dafür mehr
Facebook und Twitter prominenter (vll. wie bei whm)
Blog-Artikel und Anleitungen ebensfalls auf Startseite
Facebook- und Twitter-Links auch in Footer
Schriftart der ersten Box anpassen
5er Grid auch bei Kanalseiten verwenden
Newsletteranmeldung (ggf. auch als PopUp)

**Comment by phmLabs** [comment]
5er Grid auch bei Kanalseiten verwenden -> done

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#86
