### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#87]
Google Analytics und Cookies und so sachen.

**Comment by phmLabs** [comment]
http://www.amilio.de/we/disclaimer/

Den Text kann man über den blog.amilio.de pflegen. Die Wordpress "Page" wird dann einfach per file_get_contents eingebunden. So haben wir ein kleines CMS, ohne dass wir was programmieren müssen.

http://www.amilio.de/we/{blogartikel}/ -> blog.amilio.de/{blogartikel}/

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#87
