### ISSUE TITLE
Kanal: Header-Hintergrundfarbe ändern

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#9]
Es sollte möglich sein die Hintergrundfarbe an sein Bild anzupassen. 
- Beim Editieren des Kanals sollte ein Colorpicker erscheinen

**Comment by phmLabs** [comment]
- Als Datenbankfeld eingetragen.
- Im Template wird es ausgelesen, falls ein Hintergrundbild existiert

**Comment by phmLabs** [comment]
Im neuen Layout nicht mehr nötig.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#9
