### ISSUE TITLE
Layout: Favorit hinzufügen / entfernen

### ISSUE THREAD

**Issue by phmLabs** [thorbenheins/miolia#93]

**Comment by phmLabs** [comment]
https://dribbble.com/shots/941313-Flat-UI-Buttons-PSD-Included

Sollte auch "folgen" heißen.

**Comment by phmLabs** [comment]
Angepasst. Muss nur noch das Icon ausgetauscht werden.

**Comment by phmLabs** [comment]
Sieht glaube ich gut genug aus für die 1.0.

**Comment by thorbenheins** [comment]
This issue was moved to phmLabs/amilio#93
